# Generated by Django 2.2.16 on 2022-09-11 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 14, 21, 28, 733618, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 14, 21, 28, 733618, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
