# Generated by Django 2.2.16 on 2022-09-10 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_orders_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-year',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Оценка не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=10, message='Оценка не может быть больше 10')], verbose_name='Оценка'),
        ),
    ]
